OPENAI_API_KEY = "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"
ELEVENLABS_API_KEY = "sk_98420ab7001414e78c76a9098fd3053bc093c16dec6256e8"
